# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: luca80b.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rluca80b.proto\x12#com.modlebest.backend.router.client\" \n\rRouterRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\"9\n\x0eRouterResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t2\x80\x02\n\rRouterService\x12q\n\x06Router\x12\x32.com.modlebest.backend.router.client.RouterRequest\x1a\x33.com.modlebest.backend.router.client.RouterResponse\x12|\n\x0fRouterResStream\x12\x32.com.modlebest.backend.router.client.RouterRequest\x1a\x33.com.modlebest.backend.router.client.RouterResponse0\x01\x42\x10Z\x0einference/grpcb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'luca80b_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\016inference/grpc'
    _globals['_ROUTERREQUEST']._serialized_start = 54
    _globals['_ROUTERREQUEST']._serialized_end = 86
    _globals['_ROUTERRESPONSE']._serialized_start = 88
    _globals['_ROUTERRESPONSE']._serialized_end = 145
    _globals['_ROUTERSERVICE']._serialized_start = 148
    _globals['_ROUTERSERVICE']._serialized_end = 404
# @@protoc_insertion_point(module_scope)
