# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

import opencompass.models.luca80b_pb2 as luca80b__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION,
                                                    GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},' +
        f' but the generated code in luca80b_pb2_grpc.py depends on' +
        f' grpcio>={GRPC_GENERATED_VERSION}.' +
        f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        +
        f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},' +
        f' scheduled for release on {SCHEDULED_RELEASE_DATE}.', RuntimeWarning)


class RouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Router = channel.unary_unary(
            '/com.modlebest.backend.router.client.RouterService/Router',
            request_serializer=luca80b__pb2.RouterRequest.SerializeToString,
            response_deserializer=luca80b__pb2.RouterResponse.FromString,
            _registered_method=True)
        self.RouterResStream = channel.unary_stream(
            '/com.modlebest.backend.router.client.RouterService/RouterResStream',
            request_serializer=luca80b__pb2.RouterRequest.SerializeToString,
            response_deserializer=luca80b__pb2.RouterResponse.FromString,
            _registered_method=True)


class RouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Router(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RouterResStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Router':
        grpc.unary_unary_rpc_method_handler(
            servicer.Router,
            request_deserializer=luca80b__pb2.RouterRequest.FromString,
            response_serializer=luca80b__pb2.RouterResponse.SerializeToString,
        ),
        'RouterResStream':
        grpc.unary_stream_rpc_method_handler(
            servicer.RouterResStream,
            request_deserializer=luca80b__pb2.RouterRequest.FromString,
            response_serializer=luca80b__pb2.RouterResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'com.modlebest.backend.router.client.RouterService',
        rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler, ))
    server.add_registered_method_handlers(
        'com.modlebest.backend.router.client.RouterService',
        rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Router(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.modlebest.backend.router.client.RouterService/Router',
            luca80b__pb2.RouterRequest.SerializeToString,
            luca80b__pb2.RouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RouterResStream(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.modlebest.backend.router.client.RouterService/RouterResStream',
            luca80b__pb2.RouterRequest.SerializeToString,
            luca80b__pb2.RouterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
